import { Header } from "@/components/Header";

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Booking Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-svh bg-[#013B94]">
        <Header />
        {children}
      </body>
    </html>
  );
}
